/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
     public boolean someLibraryMethod() {
       System.out.println("HEllo World!!"); 
       System.out.println("Hola Mundo<<<<World>>>>!!"); 
       System.out.println("Hello from feature/my_feature _ 2");
       System.out.println("Hello from feature/my_feature _ 3");
       System.out.println("Hello from feature/my_feature _ 333");
       System.out.println("Hello from feature/my_feature _ 444");
       return true;
    }
}
