/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
     public boolean someLibraryMethod() {
       System.out.println("HEllo World!!"); 
       return true;
    }
}
